apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-pvc 
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi