---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp-svc
spec:
  type: LoadBalancer
  selector: 
    app: bgg
    role: app
  ports:
  - port: 8000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-deploy-app
  namespace: bggns
  labels: 
    app: bgg-deploy-app
spec: 
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: bgg
      role: app
  template:
    metadata:
      name: bgg-app
      labels: 
        app: bgg
        role: app
    spec:
      containers:
      - name: bgg-app
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent 
        envFrom:
          - secretRef:
              name: bgg-app-secret
          - configMapRef:
              name: bgg-app-config
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3