---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector: 
    app: bgg
    role: db
  ports:
  - port: 3306
    targetPort: db-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels: 
    app: bggdb-deploy
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      role: db
  template:
    metadata:
      name: bggdb-po
      labels: 
        app: bgg
        role: db
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3306
          name: db-port