---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-app-config
  namespace: bggns
  labels:
    app: bgg-config
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-app-secret
  namespace: bggns
  labels:
    app: bgg-deploy-app
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=