apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio
data:
  MINIO_ROOT_USER: admin

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==

